name: Construction test et deployement

on:
  push:
    branches:
      - main

env:
  PROJECT_VERSION: "1.0.0"

jobs:
  RealisationBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@main
      - name: Setup du JDK
        uses: actions/java@v1
      - name: Nettoyage de maven
        run: mvn ckeab package -DskipTests
